### PR TITLE
Update P06.scala

### PR DESCRIPTION
**Pull request by radekbaranowski**
my humble attempt :)

### CODE REVIEW

**Comment by jaceklaskowski** [comment]
Do `git rebase -i master` and `squash` the other commits to leave just one. Thanks.

**Comment by radekbaranowski** [comment]
Did something, not feeling comfortable with github yet :) hope all is fine
afterwards :D

cheers, Radek

2015-01-26 21:14 GMT+01:00 Jacek Laskowski <notifications@github.com>:

> Do git rebase -i master and squash the other commits to leave just one.
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaceklaskowski/scalania/pull/36#issuecomment-71529556>
> .
>



-- 
Radek Baranowski

http://middlewarehints.blogspot.com/ <http://minimalnyspalony.blox.pl>
<http://minimalnyspalony.blox.pl>http://pra-tata.blogspot.com/

**Comment by dominik223** [comment]
You changed collection/P06.scala in exercises module, it's wrong. This module should contains only function definitions. So, move your solution to answers module, there is one solution for this exercise so place your next to it. Example #28

**Comment by radekbaranowski** [comment]
Thanks for the heads up! just doing that.
radek

2015-01-27 13:45 GMT+01:00 Dominik Surowiecki <notifications@github.com>:

> You changed collection/P06.scala in exercises module, it's wrong. This
> module should contains only function definitions. So, move your solution to
> answers module, there is one solution for this exercise so place your next
> to it. Example #28 <https://github.com/jaceklaskowski/scalania/pull/28>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaceklaskowski/scalania/pull/36#issuecomment-71642255>
> .
>



-- 
Radek Baranowski

http://middlewarehints.blogspot.com/ <http://minimalnyspalony.blox.pl>
<http://minimalnyspalony.blox.pl>http://pra-tata.blogspot.com/

**Comment by jaceklaskowski** [comment]
Ping @radekbaranowski Any help needed? We're here to help.

**Comment by radekbaranowski** [comment]
No thanks, I have moved solution to Answers and removed it from exercises.
anything more to do ?

2015-01-29 11:39 GMT+01:00 Jacek Laskowski <notifications@github.com>:

> Ping @radekbaranowski <https://github.com/radekbaranowski> Any help
> needed? We're here to help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaceklaskowski/scalania/pull/36#issuecomment-72004119>
> .
>



-- 
Radek Baranowski

http://middlewarehints.blogspot.com/ <http://minimalnyspalony.blox.pl>
<http://minimalnyspalony.blox.pl>http://pra-tata.blogspot.com/

**Comment by jaceklaskowski** [comment]
There should be **one** commit to merge with master.

In the branch `patch-1` execute `git rebase -i master` and `squash` the other two commits. When you have the single commit ready `git push -f` to your remote repo on github. It's also going to tell github that the other attempts are obsolete. It helps greatly merging the changes to `master`.

Thanks!

**Comment by jaceklaskowski** [comment]
Closed as per request from @radekbaranowski in the other pull request.

**Pull request closed without merging**
